In [2]:
import numpy as np
np.random.seed(1)

In [3]:
a = np.random.rand(3, 2)
b = np.random.randint(0, 2, (2,))
a, b

(array([[4.17022005e-01, 7.20324493e-01],
        [1.14374817e-04, 3.02332573e-01],
        [1.46755891e-01, 9.23385948e-02]]),
 array([0, 1]))

In [4]:
a * b

array([[0.        , 0.72032449],
       [0.        , 0.30233257],
       [0.        , 0.09233859]])

In [5]:
c = np.random.randint(0, 2, (2, 1))
c

array([[1],
       [0]])

In [6]:
a * c

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

In [7]:
a * c.T

array([[4.17022005e-01, 0.00000000e+00],
       [1.14374817e-04, 0.00000000e+00],
       [1.46755891e-01, 0.00000000e+00]])

In [8]:
c

array([[1],
       [0]])

In [9]:
b = b[None, :]
b.shape

(1, 2)

In [10]:
a + b

array([[4.17022005e-01, 1.72032449e+00],
       [1.14374817e-04, 1.30233257e+00],
       [1.46755891e-01, 1.09233859e+00]])

In [16]:
a.T + b.squeeze()

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [15]:
a, b.squeeze()

(array([[4.17022005e-01, 7.20324493e-01],
        [1.14374817e-04, 3.02332573e-01],
        [1.46755891e-01, 9.23385948e-02]]),
 array([0, 1]))

In [17]:
loss = np.random.randn(3, 1)
weight = np.random.randn(3)
weighted_loss = loss * weight

In [18]:
weighted_loss

array([[-0.65875426,  0.27609887, -0.21580703],
       [ 1.75194714, -0.73428083,  0.57393557],
       [-1.32816276,  0.55666317, -0.43510436]])

In [19]:
loss.shape, weight.shape

((3, 1), (3,))

In [20]:
weighted_loss = loss * weight[:, None]
weighted_loss

array([[-0.65875426],
       [-0.73428083],
       [-0.43510436]])

In [21]:
weight[:, None].shape

(3, 1)

In [22]:
weighted_loss.mean()

-0.6093798165674668

In [23]:
sum(weighted_loss) / len(weighted_loss)

array([-0.60937982])