In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

%matplotlib inline

Please download only the fashion_mnist_test.csv file from this [kaggle](https://www.kaggle.com/zalando-research/fashionmnist?select=fashion-mnist_test.csv) link.

In [2]:
df = pd.read_csv("/tmp/fashion-mnist_test.csv")

We know that 10 dimensions explain 72% of the variation in images.

In [3]:
from sklearn.decomposition import PCA
images = df.iloc[:,1:].values
pca = PCA(n_components=10)
images_low_dim = pca.fit_transform(images)

See https://scikit-learn.org/stable/modules/clustering.html for overview of clustering methods.

In [5]:
from sklearn.cluster import KMeans, DBSCAN, SpectralClustering
from sklearn.mixture import GaussianMixture
from tqdm.auto import tqdm

In [6]:
models = [
    KMeans(n_clusters=11), 
    KMeans(n_clusters=10), 
    DBSCAN(min_samples=100), 
    SpectralClustering(n_clusters=10),
    GaussianMixture(n_components=10)
         ]
      
y_model_preds = [model.fit_predict(images_low_dim) for model in tqdm(models)]

/Users/sachinthaka/opt/miniconda3/lib/python3.7/site-packages/sklearn/manifold/_spectral_embedding.py:236: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"


In [7]:
y_model_preds

[array([4, 5, 2, ..., 7, 3, 9], dtype=int32),
 array([3, 9, 1, ..., 5, 6, 4], dtype=int32),
 array([-1, -1, -1, ..., -1, -1, -1]),
 array([5, 4, 6, ..., 4, 4, 6], dtype=int32),
 array([6, 3, 1, ..., 8, 8, 4])]

In [8]:
from sklearn.metrics import adjusted_rand_score

y_true = df["label"].values.squeeze()
[adjusted_rand_score(y_pred.squeeze(), y_true) for y_pred in y_model_preds]

[0.3419164046447792,
 0.36613207938952297,
 0.0,
 -3.6592747335556684e-05,
 0.4004664435422742]