In [1]:
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

In [2]:
data = load_boston()

In [3]:
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [4]:
print(data["DESCR"])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

## Get Data

In [5]:
X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["MEDV"])

In [6]:
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 13), (51, 13), (455, 1), (51, 1))

## Linear Model

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [12]:
X.shape

(506, 13)

In [59]:
medv = intercept + b1 * CRIM + b2* ZN + ... b13 *LSTAT + error

SyntaxError: invalid syntax (<ipython-input-59-f52c4b265557>, line 1)

In [13]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
y_pred = model.predict(X_test)

In [15]:
model.coef_, model.intercept_

(array([[-1.16259926e-01,  5.56061815e-02,  2.42066570e-03,
          2.58498034e+00, -1.91474547e+01,  3.54362973e+00,
         -5.86296897e-04, -1.59321860e+00,  3.16227116e-01,
         -1.20965602e-02, -9.20798781e-01,  8.75217941e-03,
         -5.18191990e-01]]),
 array([38.93532959]))

In [16]:
model.coef_.shape

(1, 13)

In [17]:
X_test.shape

(51, 13)

In [18]:
y_pred_manual = np.matmul(X_test.values, model.coef_.T) + model.intercept_

## Metrics

In [19]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [20]:
e = (y_pred - y_test)
np.square(e).mean()

MEDV    20.544275
dtype: float64

In [21]:
mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred)

(20.544274659325918, 3.745637677029239)

In [22]:
mse_our_model = mean_squared_error(y_test, y_pred)

In [23]:
r2_score(y_test, y_pred)

0.7786386580298901

In [24]:
mse_bad_model = mean_squared_error(y_test, y_train.mean().values * np.ones_like(y_test))

In [25]:
1 - mse_our_model / mse_bad_model

0.7787361370918796

In [26]:
y_train.mean().values

array([22.55318681])

In [27]:
y_test.values

array([[28.2],
       [23.9],
       [16.6],
       [22. ],
       [20.8],
       [23. ],
       [27.9],
       [14.5],
       [21.5],
       [22.6],
       [23.7],
       [31.2],
       [19.3],
       [19.4],
       [19.4],
       [27.9],
       [13.9],
       [50. ],
       [24.1],
       [14.6],
       [16.2],
       [15.6],
       [23.8],
       [25. ],
       [23.5],
       [ 8.3],
       [13.5],
       [17.5],
       [43.1],
       [11.5],
       [24.1],
       [18.5],
       [50. ],
       [12.6],
       [19.8],
       [24.5],
       [14.9],
       [36.2],
       [11.9],
       [19.1],
       [22.6],
       [20.7],
       [30.1],
       [13.3],
       [14.6],
       [ 8.4],
       [50. ],
       [12.7],
       [25. ],
       [18.6],
       [29.8]])

In [28]:
np.ones_like(y_test) * y_train.mean().values

array([[22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22.55318681],
       [22

In [29]:
mean_squared_error(y_test, np.ones_like(y_test) * y_train.mean().values)

92.84966098534088

In [30]:
r2_score(y_test, y_pred)

0.7786386580298901

In [31]:
1 - mean_squared_error(y_test, y_pred) / mean_squared_error(y_test, np.ones_like(y_test) * y_test.mean().values)

0.7786386580298901